### ISSUE TITLE
Error with SpatialFullConvolution when running on GPU on Ubuntu 16.04 with Cuda 7.5

### ISSUE THREAD

**Issue by jamiis** [soumith/dcgan.torch#30]
Probably not the wisest decision to upgrade to 16.04 already but it's (basically) too late now. The error message below persists after completely reinstalling torch and all deps. I'm running Cuda 7.5 and have various cudnn primitive binding libs install in `/usr/local/cuda-7.5/lib64`. Cuda is in my PATH and also have LD_LIBRARY_PATH, CUDA_HOME, CUDA_LIB, CUDA_BIN, CPATH, LIBRARY_PATH setup. I'm so lost haha

```
jamis@jamis:~/src/dcgan.torch$ gpu=1 net=checkpoints/celebA_25_net_G.t7 th generate.lua
{
  gpu : 1
  noisemode : "random"
  name : "generation1"
  noisetype : "normal"
  batchSize : 32
  net : "checkpoints/celebA_25_net_G.t7"
  imsize : 1
  nz : 100
  display : 1
}
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> output]
  (1): nn.SpatialFullConvolution(100 -> 512, 4x4)
  (2): nn.SpatialBatchNormalization
  (3): nn.ReLU
  (4): nn.SpatialFullConvolution(512 -> 256, 4x4, 2,2, 1,1)
  (5): nn.SpatialBatchNormalization
  (6): nn.ReLU
  (7): nn.SpatialFullConvolution(256 -> 128, 4x4, 2,2, 1,1)
  (8): nn.SpatialBatchNormalization
  (9): nn.ReLU
  (10): nn.SpatialFullConvolution(128 -> 64, 4x4, 2,2, 1,1)
  (11): nn.SpatialBatchNormalization
  (12): nn.ReLU
  (13): nn.SpatialFullConvolution(64 -> 3, 4x4, 2,2, 1,1)
  (14): nn.Tanh
}
/home/jamis/torch/install/bin/luajit: /home/jamis/torch/install/share/lua/5.1/nn/Container.lua:67:
In 1 module of nn.Sequential:
...h/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:114: attempt to perform arithmetic on field 'adjW' (a nil value)
stack traceback:
        ...h/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:114: in function 'createIODescriptors'
        ...h/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:312: in function <...h/install/share/lua/5.1/cudnn/SpatialFullConvolution.lua:310>
        [C]: in function 'xpcall'
        /home/jamis/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/jamis/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        /home/jamis/torch/install/share/lua/5.1/optnet/init.lua:376: in function 'optimizeMemory'
        generate.lua:82: in main chunk
        [C]: in function 'dofile'
        ...amis/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        /home/jamis/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        /home/jamis/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        /home/jamis/torch/install/share/lua/5.1/optnet/init.lua:376: in function 'optimizeMemory'
        generate.lua:82: in main chunk
        [C]: in function 'dofile'
        ...amis/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405d50
```

**Comment by soumith** [comment]
should be fixed if you install the latest cudnn.torch bindings: luarocks install torch
fixed via commit: https://github.com/soumith/cudnn.torch/commit/556c272b8be5b3b61a8f1f2b8a7daf8ce73681c1

**Comment by ilija139** [comment]
Actually, it's not fixed. Or maybe is re-introduced. Anyway, I get the same error with the latest versions. 

The problem is `self.adjW` and `self.adjH` are still not initialized when calling `SpatialFullConvolution:createIODescriptors(...)`. `SpatialFullConvolution:read(...)` is never called when the network is created via `torch.load(...)`, so the fix doesn't solve the problem. 

One way to solve this is to add the two lines:
```
self.adjW = self.adjW or 0
self.adjH = self.adjH or 0
```
to `cudnn.SpatialFullConvolution.lua` line 111. 

Although I'm not sure if this is the correct way and does not introduce new problems.
